# import = ["~/.config/alacritty/base16_default_dark.toml"]
# import = ["~/.config/alacritty/citylights.toml"] 

[cursor.style]
blinking = "Always"
shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "SauceCodePro Nerd Font Bold"

[font.normal]
family = "SauceCodePro Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
command = { program = "alacritty", args = ["msg", "config", "window.opacity=1.0"] }
key = "O"
mods = "Control|Shift"

[[keyboard.bindings]]
command = { program = "alacritty", args = ["msg", "config", "-r"] }
key = "R"
mods = "Control|Shift"

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.7333

[window.padding]
x = 12
y = 8

[terminal]
